import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    name: "Brake Rotor",
    price: "5000",
    src: "./public/images/tiresWheels/brakeRotor.jpg",
    rating: 4,
    categoryName: "Tires & Wheels",
  },
  {
    _id: uuid(),
    name: "Brandix Brake Kit",
    price: "5000",
    src: "./public/images/tiresWheels/brandixBrakeKit.jpg",
    rating: 4,
    categoryName: "Tires & Wheels",
  },
  {
    _id: uuid(),
    name: "Glossy Gray Aluminium Wheel",
    price: "5000",
    src: "./public/images/tiresWheels/glossyGrayAluminiumWheel.jpg",
    rating: 4,
    categoryName: "Tires & Wheels",
  },
  {
    _id: uuid(),
    name: "Adjustable Spanner",
    price: "5000",
    src: "./public/images/tools&Garage/adjustableSpanner.jpg",
    rating: 4,
    categoryName: "Tools & Garage",
  },
  {
    _id: uuid(),
    name: "Spanner Kit",
    price: "5000",
    src: "./public/images/tools&Garage/spannerKit.jpg",
    rating: 4,
    categoryName: "Tools & Garage",
  },
  {
    _id: uuid(),
    name: "Wrench",
    price: "5000",
    src: "./public/images/tools&Garage/wrench.jpg",
    rating: 4,
    categoryName: "Tools & Garage",
  },
  {
    _id: uuid(),
    name: "Coolant",
    price: "5000",
    src: "./public/images/oil&Libricant/coolant.jpg",
    rating: 4,
    categoryName: "Oil & Lubircants",
  },
  {
    _id: uuid(),
    name: "Diesel Oil",
    price: "5000",
    src: "./public/images/oil&Libricant/dieselOil.jpg",
    rating: 4,
    categoryName: "Oil & Lubricants",
  },
  {
    _id: uuid(),
    name: "Graphene Ceramic Coating",
    price: "5000",
    src: "./public/images/oil&Libricant/grapheneCeramicCoating.jpg",
    rating: 4,
    categoryName: "Oil & Lubricants",
  },
  {
    _id: uuid(),
    name: "Back Driver Seat",
    price: "5000",
    src: "./public/images/interiorParts/backDriverSeat.jpg",
    rating: 4,
    categoryName: "Interior Parts",
  },
  {
    _id: uuid(),
    name: "Car Alarm Along With Charger",
    price: "5000",
    src: "./public/images/interiorParts/carAlarmCharger.jpg",
    rating: 4,
    categoryName: "interiorParts",
  },
  {
    _id: uuid(),
    name: "Wiper Blades",
    price: "5000",
    src: "./public/images/interiorParts/wiperBlades.jpg",
    rating: 4,
    categoryName: "Interior Parts",
  },
  {
    _id: uuid(),
    name: "Left HeadLight",
    price: "5000",
    src: "./public/images/headlights&Lighting/leftHeadLight.jpg",
    rating: 4,
    categoryName: "HeadLights & Lighting",
  },
  {
    _id: uuid(),
    name: "Lumen Custom HeadLight",
    price: "5000",
    src: "./public/images/headlights&Lighting/lumenCustomHeadLight.jpg",
    rating: 4,
    categoryName: "HeadLights & Lighting",
  },
  {
    _id: uuid(),
    name: "Spyder Projector",
    price: "5000",
    src: "./public/images/headlights&Lighting/spyderProjector.jpg",
    rating: 4,
    categoryName: "HeadLights & Lighting",
  },
  {
    _id: uuid(),
    name: "Fuel Filter",
    price: "5000",
    src: "./public/images/fuelSystem/fuelFilter.jpg",
    rating: 4,
    categoryName: "Fuel System",
  },
  {
    _id: uuid(),
    name: "Fuel Injector",
    price: "5000",
    src: "./public/images/fuelSystem/fuelInjector.jpg",
    rating: 4,
    categoryName: "Fuel System",
  },
  {
    _id: uuid(),
    name: "Twin Exhaust Pipe",
    price: "5000",
    src: "./public/images/fuelSystem/twinExhaustPipe.jpg",
    rating: 4,
    categoryName: "Fuel System",
  },
  {
    _id: uuid(),
    name: "Engine Block",
    price: "5000",
    src: "./public/images/bodyParts/engineBlock.jpg",
    rating: 4,
    categoryName: "Body Parts",
  },
  {
    _id: uuid(),
    name: "Gear Box",
    price: "5000",
    src: "./public/images/bodyParts/gearBox.jpg",
    rating: 4,
    categoryName: "Body Parts",
  },
  {
    _id: uuid(),
    name: "Radiator",
    price: "5000",
    src: "./public/images/bodyParts/radiator.jpg",
    rating: 4,
    categoryName: "Body Parts",
  },
];
